// USER

### Obtiene todos los usuarios

GET http://localhost:3000/api/user/ HTTP/1.1

### Ejemplo con Viper

GET http://localhost:3000/api/user/67362fc86af1b60c160fbdd1 HTTP/1.1

### Creo un usuario (Killjoy)

POST http://localhost:3000/api/user/ HTTP/1.1
Content-Type: application/json

{
    "username": "Killjoy",
    "fullname": "Klara Böhringer",
    "description": "Sentinel from Germany.",
    "email": "kj23@gmail.com",
    "profile_pic": "https://static.wikia.nocookie.net/valorant/images/1/15/Killjoy_icon.png/revision/latest/smart/width/250/height/250?cb=20230523180727",
     "pwd": "r4z3_360"

}

### Modifico el apellido de Jett (Quito una 'o')

PUT http://localhost:3000/api/user/67365186eeed3b908fca32a1 HTTP/1.1
Content-Type: application/json

{
    "username": "Jett",
    "fullname": "Sunwoo Han",
    "description": "Duelist from South Korea.",
    "email": "jett123@gmail.com",
    "profile_pic": "https://static.wikia.nocookie.net/valorant-lore/images/2/2a/Jett_-_Avatar.png/revision/latest?cb=20230629181633",
    "pwd": "kimchi.1"
}


### Borro a Killjoy

DELETE http://localhost:3000/api/user/-- HTTP/1.1

// POST

###

GET http://localhost:3000/api/post/ HTTP/1.1

### Devuelve el post de una foto grupal posteada por Jett

GET http://localhost:3000/api/post/673785e9f3441da8d75fc8f4 HTTP/1.1

###

POST http://localhost:3000/api/post/ HTTP/1.1
Content-Type: application/json

{
    "user": "67365186eeed3b908fca32a1",
    "txt": "¡Foto grupal!",
    "img": "https://www.riotgames.com/darkroom/730/e501341e485a96f9ada46fc532cff21e:45a88ae13d76f0300bd958de6906a0f2/valorant-community-artist-final.png"
}

###

PUT http://localhost:3000/api/post/673785e9f3441da8d75fc8f4 HTTP/1.1
Content-Type: application/json

{
    "user": "67365186eeed3b908fca32a1",
    "txt": "¡Foto grupal! (Falta Harbor :()",
    "img": "https://www.riotgames.com/darkroom/730/e501341e485a96f9ada46fc532cff21e:45a88ae13d76f0300bd958de6906a0f2/valorant-community-artist-final.png"
}

###

DELETE http://localhost:3000/api/post/6736553feeed3b908fca32c1 HTTP/1.1

// FOLLOWER

###

GET http://localhost:3000/api/follower/ HTTP/1.1

###

GET http://localhost:3000/api/follower/6736736543deeed3b908fca32b2 HTTP/1.1

### Sova sigue a Viper

POST http://localhost:3000/api/follower/ HTTP/1.1
Content-Type: application/json

{
    "user_follower": "67362fa66af1b60c160fbdcf",
    "user_followed": "67362fc86af1b60c160fbdd1"
}

###

DELETE http://localhost:3000/api/follower/673673658eceeed3b908fca32da HTTP/1.1

// LIKE

###

GET http://localhost:3000/api/like/ HTTP/1.1

###

GET http://localhost:3000/api/like/id HTTP/1.1

### A Sova le gusta el post de la foto grupal

POST http://localhost:3000/api/like/ HTTP/1.1
Content-Type: application/json

{
    "user_liking": "67362fa66af1b60c160fbdcf",
    "liked": "id"
}

###

DELETE http://localhost:3000/api/like/id HTTP/1.1

// FEED

###

GET http://localhost:3000/api/feed/user/id HTTP/1.1